language: node_js
matrix:
  fast_finish: true
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
deploy:
  provider: npm
  email: npm@cozycloud.cc
  api_key:
    secure: T74cGa4BGluvE0LjwvVIHXUhPOZ0e22TI4O4ZUW7AtHPp9fucNJ7AIA+ZTb4n2sl+tLNI4wiCPnSUGUkloKVwCh3ltAxv08glM+DXmNWVYa+Z3DrbiXbpgWU3c2rfi87wjwxGYqaiSrEc6Re8MKKF79H6YA2epzume4u3Hd3QB1Vyg/UAm9p2LNrR4CCEeVljZ+AEowCGlJVj4gtUbLrQi/u0aWR6wc5+lYeYNb3ILkq86wMigyp+pMU78K4m2BiXEvd1eMNekddOYhS1a6/HZT+R4NJ26f7qKGggC1Yet6BoxoE+OTnP5kKeKYAZEpEybX41iABpxeebKPTue0sII1b4Ufr985R8H3qNVubATg0yaU2g1+xYU+plOBEpnmaEmki1DaASoCCsdRyxPnvrObfU4Xf9M2xM+wK8ILpuYWUW447SCtDFNnfvHIZ3/J+rWYUk4Avd8dxJucmEtbuajZ2D5kXaD9dYdOwEYAVHouuTMZudGI6xbM1S2wAoDhCyEXsrLpy+ArxnkoqdBXgGJayYOEqoAK4MbAffCqYSJdPLBb8JNaLHDQ1x7QeHT1pvvcNaNAoKVr6tWG1e2zhQ/+EtXyCHKacNWbO3lSdCZT0oGSO9rqMEch5XKVbibbj+VfADIOVOpsnH10necFJlPkGb3/PHY3QKBUyNrX6J6Q=
  on:
    tags: true
    repo: cozy/cozy-konnector-libs
